/**
 * pt-i18n.js — Piererra Tools i18n system
 * 30 languages · 85 keys · localStorage key: 'pt-lang'
 *
 * Usage:
 *   ptI18n.t('key')               — get translated string
 *   ptI18n.t('key', {n: 1})       — with variable interpolation
 *   ptI18n.apply(langCode)        — walk DOM and apply translations
 *   ptI18n.init()                 — call on DOMContentLoaded
 *
 * HTML attributes honoured:
 *   data-i18n="key"               — sets textContent
 *   data-i18n-placeholder="key"   — sets placeholder
 *   data-i18n-title="key"         — sets title
 *   data-i18n-label="key"         — sets aria-label
 */

(function (window) {
  'use strict';

  /* ─────────────────────────────────────────────────────────
     TRANSLATION DICTIONARY
  ───────────────────────────────────────────────────────── */
  var dict = {

    /* ── Portal ──────────────────────────────────────────── */
    'site.title':         { en:'PIERERRA TOOLS', fr:'PIERERRA TOOLS', es:'PIERERRA TOOLS', de:'PIERERRA TOOLS', pt:'PIERERRA TOOLS', ru:'PIERERRA TOOLS', 'zh-hans':'PIERERRA TOOLS', 'zh-hant':'PIERERRA TOOLS', ja:'PIERERRA TOOLS', ko:'PIERERRA TOOLS', ar:'PIERERRA TOOLS', hi:'PIERERRA TOOLS', it:'PIERERRA TOOLS', nl:'PIERERRA TOOLS', pl:'PIERERRA TOOLS', tr:'PIERERRA TOOLS', id:'PIERERRA TOOLS', vi:'PIERERRA TOOLS', th:'PIERERRA TOOLS', uk:'PIERERRA TOOLS', sv:'PIERERRA TOOLS', da:'PIERERRA TOOLS', fi:'PIERERRA TOOLS', no:'PIERERRA TOOLS', cs:'PIERERRA TOOLS', hu:'PIERERRA TOOLS', ro:'PIERERRA TOOLS', el:'PIERERRA TOOLS', ms:'PIERERRA TOOLS', fa:'PIERERRA TOOLS' },
    'site.tagline':       { en:'// a personal toolbox', fr:'// une boîte à outils personnelle', es:'// una caja de herramientas personal', de:'// eine persönliche Toolbox', pt:'// uma caixa de ferramentas pessoal', ru:'// личный набор инструментов', 'zh-hans':'// 个人工具箱', 'zh-hant':'// 個人工具箱', ja:'// 個人ツールボックス', ko:'// 개인 도구 모음', ar:'// مجموعة أدوات شخصية', hi:'// एक व्यक्तिगत टूलबॉक्स', it:'// una cassetta degli attrezzi personale', nl:'// een persoonlijke gereedschapskist', pl:'// osobista skrzynka z narzędziami', tr:'// kişisel bir araç kutusu', id:'// kotak alat pribadi', vi:'// hộp công cụ cá nhân', th:'// กล่องเครื่องมือส่วนตัว', uk:'// особистий набір інструментів', sv:'// en personlig verktygslåda', da:'// en personlig værktøjskasse', fi:'// henkilökohtainen työkalupakki', no:'// en personlig verktøykasse', cs:'// osobní sada nástrojů', hu:'// személyes eszköztár', ro:'// o cutie de instrumente personală', el:'// μια προσωπική εργαλειοθήκη', ms:'// kotak alat peribadi', fa:'// جعبه ابزار شخصی' },
    'portal.select':      { en:'// SELECT TOOL', fr:'// SÉLECTIONNER UN OUTIL', es:'// SELECCIONAR HERRAMIENTA', de:'// WERKZEUG AUSWÄHLEN', pt:'// SELECIONAR FERRAMENTA', ru:'// ВЫБРАТЬ ИНСТРУМЕНТ', 'zh-hans':'// 选择工具', 'zh-hant':'// 選擇工具', ja:'// ツールを選択', ko:'// 도구 선택', ar:'// اختر الأداة', hi:'// उपकरण चुनें', it:'// SELEZIONA STRUMENTO', nl:'// SELECTEER TOOL', pl:'// WYBIERZ NARZĘDZIE', tr:'// ARAÇ SEÇ', id:'// PILIH ALAT', vi:'// CHỌN CÔNG CỤ', th:'// เลือกเครื่องมือ', uk:'// ОБЕРІТЬ ІНСТРУМЕНТ', sv:'// VÄLJ VERKTYG', da:'// VÆLG VÆRKTØJ', fi:'// VALITSE TYÖKALU', no:'// VELG VERKTØY', cs:'// VYBERTE NÁSTROJ', hu:'// VÁLASSZON ESZKÖZT', ro:'// SELECTAȚI INSTRUMENTUL', el:'// ΕΠΙΛΟΓΗ ΕΡΓΑΛΕΙΟΥ', ms:'// PILIH ALAT', fa:'// انتخاب ابزار' },
    'portal.coming_soon': { en:'COMING SOON', fr:'BIENTÔT DISPONIBLE', es:'PRÓXIMAMENTE', de:'DEMNÄCHST', pt:'EM BREVE', ru:'СКОРО', 'zh-hans':'即将推出', 'zh-hant':'即將推出', ja:'近日公開', ko:'출시 예정', ar:'قريباً', hi:'जल्द आ रहा है', it:'PROSSIMAMENTE', nl:'BINNENKORT', pl:'WKRÓTCE', tr:'YAKINDA', id:'SEGERA HADIR', vi:'SẮP RA MẮT', th:'เร็วๆ นี้', uk:'НЕЗАБАРОМ', sv:'KOMMER SNART', da:'KOMMER SNART', fi:'TULOSSA PIAN', no:'KOMMER SNART', cs:'BRZY', hu:'HAMAROSAN', ro:'ÎN CURÂND', el:'ΣΎΝΤΟΜΑ', ms:'AKAN DATANG', fa:'به زودی' },
    'portal.next_tool':   { en:'Next tool in development.', fr:'Prochain outil en développement.', es:'Próxima herramienta en desarrollo.', de:'Nächstes Werkzeug in Entwicklung.', pt:'Próxima ferramenta em desenvolvimento.', ru:'Следующий инструмент в разработке.', 'zh-hans':'下一个工具正在开发中。', 'zh-hant':'下一個工具正在開發中。', ja:'次のツールを開発中です。', ko:'다음 도구를 개발 중입니다.', ar:'الأداة التالية قيد التطوير.', hi:'अगला उपकरण विकास में है।', it:'Prossimo strumento in sviluppo.', nl:'Volgend gereedschap in ontwikkeling.', pl:'Następne narzędzie w trakcie tworzenia.', tr:'Sonraki araç geliştiriliyor.', id:'Alat berikutnya sedang dikembangkan.', vi:'Công cụ tiếp theo đang phát triển.', th:'เครื่องมือถัดไปอยู่ระหว่างการพัฒนา', uk:'Наступний інструмент у розробці.', sv:'Nästa verktyg under utveckling.', da:'Næste værktøj under udvikling.', fi:'Seuraava työkalu kehitteillä.', no:'Neste verktøy under utvikling.', cs:'Další nástroj ve vývoji.', hu:'A következő eszköz fejlesztés alatt.', ro:'Următorul instrument în dezvoltare.', el:'Επόμενο εργαλείο υπό ανάπτυξη.', ms:'Alat seterusnya dalam pembangunan.', fa:'ابزار بعدی در حال توسعه است.' },
    'portal.game_tool':   { en:'GAME TOOL', fr:'OUTIL JEU', es:'HERRAMIENTA JUEGO', de:'SPIELZEUG', pt:'FERRAMENTA JOGO', ru:'ИГРОВОЙ ИНСТРУМЕНТ', 'zh-hans':'游戏工具', 'zh-hant':'遊戲工具', ja:'ゲームツール', ko:'게임 도구', ar:'أداة ألعاب', hi:'गेम टूल', it:'STRUMENTO GIOCO', nl:'SPELTOOL', pl:'NARZĘDZIE DO GRY', tr:'OYUN ARACI', id:'ALAT GAME', vi:'CÔNG CỤ GAME', th:'เครื่องมือเกม', uk:'ІГРОВИЙ ІНСТРУМЕНТ', sv:'SPELVERKTYG', da:'SPILVÆRKTØJ', fi:'PELITYÖKALU', no:'SPILLVERKTØY', cs:'HERNÍ NÁSTROJ', hu:'JÁTÉKESZKÖZ', ro:'INSTRUMENT JOC', el:'ΕΡΓΑΛΕΙΟ ΠΑΙΧΝΙΔΙΟΥ', ms:'ALAT PERMAINAN', fa:'ابزار بازی' },
    'footer.built_by':    { en:'PIERERRA TOOLS · built by Piererra', fr:'PIERERRA TOOLS · créé par Piererra', es:'PIERERRA TOOLS · creado por Piererra', de:'PIERERRA TOOLS · erstellt von Piererra', pt:'PIERERRA TOOLS · criado por Piererra', ru:'PIERERRA TOOLS · создано Piererra', 'zh-hans':'PIERERRA TOOLS · 由 Piererra 构建', 'zh-hant':'PIERERRA TOOLS · 由 Piererra 建立', ja:'PIERERRA TOOLS · Piererra 作', ko:'PIERERRA TOOLS · Piererra 제작', ar:'PIERERRA TOOLS · بناء بواسطة Piererra', hi:'PIERERRA TOOLS · Piererra द्वारा निर्मित', it:'PIERERRA TOOLS · creato da Piererra', nl:'PIERERRA TOOLS · gemaakt door Piererra', pl:'PIERERRA TOOLS · stworzone przez Piererra', tr:'PIERERRA TOOLS · Piererra tarafından yapıldı', id:'PIERERRA TOOLS · dibuat oleh Piererra', vi:'PIERERRA TOOLS · được tạo bởi Piererra', th:'PIERERRA TOOLS · สร้างโดย Piererra', uk:'PIERERRA TOOLS · створено Piererra', sv:'PIERERRA TOOLS · byggd av Piererra', da:'PIERERRA TOOLS · bygget af Piererra', fi:'PIERERRA TOOLS · Piererra rakentama', no:'PIERERRA TOOLS · laget av Piererra', cs:'PIERERRA TOOLS · vytvořeno Piererra', hu:'PIERERRA TOOLS · készítette Piererra', ro:'PIERERRA TOOLS · creat de Piererra', el:'PIERERRA TOOLS · κατασκευή από Piererra', ms:'PIERERRA TOOLS · dibina oleh Piererra', fa:'PIERERRA TOOLS · ساخته Piererra' },

    /* ── Editor — Nav & Header ───────────────────────────── */
    'nav.back':           { en:'← Piererra Tools', fr:'← Piererra Tools', es:'← Piererra Tools', de:'← Piererra Tools', pt:'← Piererra Tools', ru:'← Piererra Tools', 'zh-hans':'← Piererra Tools', 'zh-hant':'← Piererra Tools', ja:'← Piererra Tools', ko:'← Piererra Tools', ar:'Piererra Tools ←', hi:'← Piererra Tools', it:'← Piererra Tools', nl:'← Piererra Tools', pl:'← Piererra Tools', tr:'← Piererra Tools', id:'← Piererra Tools', vi:'← Piererra Tools', th:'← Piererra Tools', uk:'← Piererra Tools', sv:'← Piererra Tools', da:'← Piererra Tools', fi:'← Piererra Tools', no:'← Piererra Tools', cs:'← Piererra Tools', hu:'← Piererra Tools', ro:'← Piererra Tools', el:'← Piererra Tools', ms:'← Piererra Tools', fa:'Piererra Tools ←' },
    'editor.title':       { en:'NEED FOR SPEED UNDERGROUND 2', fr:'NEED FOR SPEED UNDERGROUND 2', es:'NEED FOR SPEED UNDERGROUND 2', de:'NEED FOR SPEED UNDERGROUND 2', pt:'NEED FOR SPEED UNDERGROUND 2', ru:'NEED FOR SPEED UNDERGROUND 2', 'zh-hans':'NEED FOR SPEED UNDERGROUND 2', 'zh-hant':'NEED FOR SPEED UNDERGROUND 2', ja:'NEED FOR SPEED UNDERGROUND 2', ko:'NEED FOR SPEED UNDERGROUND 2', ar:'NEED FOR SPEED UNDERGROUND 2', hi:'NEED FOR SPEED UNDERGROUND 2', it:'NEED FOR SPEED UNDERGROUND 2', nl:'NEED FOR SPEED UNDERGROUND 2', pl:'NEED FOR SPEED UNDERGROUND 2', tr:'NEED FOR SPEED UNDERGROUND 2', id:'NEED FOR SPEED UNDERGROUND 2', vi:'NEED FOR SPEED UNDERGROUND 2', th:'NEED FOR SPEED UNDERGROUND 2', uk:'NEED FOR SPEED UNDERGROUND 2', sv:'NEED FOR SPEED UNDERGROUND 2', da:'NEED FOR SPEED UNDERGROUND 2', fi:'NEED FOR SPEED UNDERGROUND 2', no:'NEED FOR SPEED UNDERGROUND 2', cs:'NEED FOR SPEED UNDERGROUND 2', hu:'NEED FOR SPEED UNDERGROUND 2', ro:'NEED FOR SPEED UNDERGROUND 2', el:'NEED FOR SPEED UNDERGROUND 2', ms:'NEED FOR SPEED UNDERGROUND 2', fa:'NEED FOR SPEED UNDERGROUND 2' },
    'editor.subtitle':    { en:'Save Editor', fr:'Éditeur de sauvegarde', es:'Editor de guardado', de:'Speicherstand-Editor', pt:'Editor de save', ru:'Редактор сохранений', 'zh-hans':'存档编辑器', 'zh-hant':'存檔編輯器', ja:'セーブエディタ', ko:'세이브 에디터', ar:'محرر الحفظ', hi:'सेव एडिटर', it:'Editor salvataggio', nl:'Save editor', pl:'Edytor zapisu', tr:'Kayıt editörü', id:'Editor simpanan', vi:'Trình sửa lưu', th:'ตัวแก้ไขเซฟ', uk:'Редактор збережень', sv:'Sparfilsredigerare', da:'Gemfilredigering', fi:'Tallennuseditori', no:'Lagringsredigerer', cs:'Editor uložené hry', hu:'Mentés szerkesztő', ro:'Editor salvare', el:'Επεξεργαστής αποθήκευσης', ms:'Penyunting simpanan', fa:'ویرایشگر ذخیره' },
    'editor.by':          { en:'by Piererra', fr:'par Piererra', es:'por Piererra', de:'von Piererra', pt:'por Piererra', ru:'от Piererra', 'zh-hans':'由 Piererra 制作', 'zh-hant':'由 Piererra 製作', ja:'Piererra 作', ko:'Piererra 제작', ar:'بواسطة Piererra', hi:'Piererra द्वारा', it:'di Piererra', nl:'door Piererra', pl:'przez Piererra', tr:'Piererra tarafından', id:'oleh Piererra', vi:'bởi Piererra', th:'โดย Piererra', uk:'від Piererra', sv:'av Piererra', da:'af Piererra', fi:'Piererra tekemä', no:'av Piererra', cs:'od Piererra', hu:'Piererra által', ro:'de Piererra', el:'από Piererra', ms:'oleh Piererra', fa:'توسط Piererra' },

    /* ── Editor — Dropzone ───────────────────────────────── */
    'drop.title':         { en:'Drop your save file here', fr:'Déposez votre fichier de sauvegarde ici', es:'Suelta tu archivo de guardado aquí', de:'Speicherdatei hier ablegen', pt:'Solte seu arquivo de save aqui', ru:'Перетащите файл сохранения сюда', 'zh-hans':'将存档文件拖放到此处', 'zh-hant':'將存檔拖放到此處', ja:'セーブファイルをここにドロップ', ko:'세이브 파일을 여기에 드롭', ar:'أسقط ملف الحفظ هنا', hi:'सेव फ़ाइल यहाँ छोड़ें', it:'Trascina il file di salvataggio qui', nl:'Zet je savebestand hier neer', pl:'Upuść plik zapisu tutaj', tr:'Kayıt dosyanı buraya bırak', id:'Letakkan file simpanan di sini', vi:'Thả tệp lưu vào đây', th:'วางไฟล์เซฟที่นี่', uk:'Перетягніть файл збереження сюди', sv:'Släpp din sparfil här', da:'Slip din gemfil her', fi:'Pudota tallennustiedosto tähän', no:'Slipp lagringsfilen her', cs:'Přetáhněte soubor uložené hry sem', hu:'Húzza ide a mentésfájlt', ro:'Aruncați fișierul de salvare aici', el:'Ρίξτε το αρχείο αποθήκευσης εδώ', ms:'Lepaskan fail simpanan di sini', fa:'فایل ذخیره را اینجا رها کنید' },
    'drop.or_browse':     { en:'or click to browse', fr:'ou cliquez pour parcourir', es:'o haz clic para buscar', de:'oder klicken zum Durchsuchen', pt:'ou clique para procurar', ru:'или нажмите для выбора', 'zh-hans':'或点击浏览', 'zh-hant':'或點擊瀏覽', ja:'またはクリックして選択', ko:'또는 클릭하여 찾기', ar:'أو انقر للتصفح', hi:'या ब्राउज़ करने के लिए क्लिक करें', it:'o clicca per sfogliare', nl:'of klik om te bladeren', pl:'lub kliknij, aby przeglądać', tr:'veya tıklayarak seç', id:'atau klik untuk pilih', vi:'hoặc nhấp để duyệt', th:'หรือคลิกเพื่อเรียกดู', uk:'або клацніть для перегляду', sv:'eller klicka för att bläddra', da:'eller klik for at gennemse', fi:'tai napsauta selataksesi', no:'eller klikk for å bla', cs:'nebo klikněte pro procházení', hu:'vagy kattintson a tallózáshoz', ro:'sau faceți clic pentru a răsfoi', el:'ή κάντε κλικ για αναζήτηση', ms:'atau klik untuk semak imbas', fa:'یا برای مرور کلیک کنید' },
    'drop.or_new':        { en:'or load an existing save', fr:'ou charger une sauvegarde existante', es:'o carga un guardado existente', de:'oder vorhandenen Spielstand laden', pt:'ou carregue um save existente', ru:'или загрузите существующее сохранение', 'zh-hans':'或加载现有存档', 'zh-hant':'或載入現有存檔', ja:'または既存のセーブを読み込む', ko:'또는 기존 세이브 불러오기', ar:'أو حمّل حفظاً موجوداً', hi:'या मौजूदा सेव लोड करें', it:'o carica un salvataggio esistente', nl:'of laad een bestaande save', pl:'lub wczytaj istniejący zapis', tr:'ya da mevcut bir kaydı yükle', id:'atau muat simpanan yang ada', vi:'hoặc tải bản lưu hiện có', th:'หรือโหลดเซฟที่มีอยู่', uk:'або завантажте наявне збереження', sv:'eller ladda en befintlig sparfil', da:'eller indlæs en eksisterende gemfil', fi:'tai lataa olemassa oleva tallennus', no:'eller last inn en eksisterende lagring', cs:'nebo načtěte existující uloženou hru', hu:'vagy töltsön be meglévő mentést', ro:'sau încărcați o salvare existentă', el:'ή φορτώστε υπάρχουσα αποθήκευση', ms:'atau muat simpanan sedia ada', fa:'یا یک ذخیره موجود بارگذاری کنید' },
    'drop.backup':        { en:'Auto-download backup on load', fr:'Sauvegarde automatique au chargement', es:'Copia de seguridad automática al cargar', de:'Backup beim Laden automatisch herunterladen', pt:'Backup automático ao carregar', ru:'Автозагрузка резервной копии при загрузке', 'zh-hans':'加载时自动下载备份', 'zh-hant':'載入時自動下載備份', ja:'読み込み時に自動バックアップ', ko:'로드 시 자동 백업 다운로드', ar:'تنزيل نسخة احتياطية تلقائياً عند التحميل', hi:'लोड पर स्वतः बैकअप डाउनलोड', it:'Scarica backup automatico al caricamento', nl:'Automatisch backup downloaden bij laden', pl:'Automatyczne pobieranie kopii przy ładowaniu', tr:'Yüklemede otomatik yedek indir', id:'Unduh backup otomatis saat memuat', vi:'Tự động tải bản sao lưu khi tải', th:'ดาวน์โหลดสำรองอัตโนมัติเมื่อโหลด', uk:'Автозавантаження резервної копії при завантаженні', sv:'Ladda ner backup automatiskt vid laddning', da:'Automatisk backup-download ved indlæsning', fi:'Lataa varmuuskopio automaattisesti', no:'Automatisk nedlasting av sikkerhetskopi', cs:'Automatické stažení zálohy při načtení', hu:'Automatikus biztonsági mentés betöltéskor', ro:'Descărcare automată backup la încărcare', el:'Αυτόματη λήψη αντιγράφου ασφαλείας', ms:'Muat turun sandaran automatik semasa muat', fa:'بارگیری خودکار پشتیبان هنگام بارگذاری' },

    /* ── Editor — Info Bar ───────────────────────────────── */
    'info.profile':       { en:'PROFILE', fr:'PROFIL', es:'PERFIL', de:'PROFIL', pt:'PERFIL', ru:'ПРОФИЛЬ', 'zh-hans':'档案', 'zh-hant':'檔案', ja:'プロフィール', ko:'프로필', ar:'الملف', hi:'प्रोफ़ाइल', it:'PROFILO', nl:'PROFIEL', pl:'PROFIL', tr:'PROFİL', id:'PROFIL', vi:'HỒ SƠ', th:'โปรไฟล์', uk:'ПРОФІЛЬ', sv:'PROFIL', da:'PROFIL', fi:'PROFIILI', no:'PROFIL', cs:'PROFIL', hu:'PROFIL', ro:'PROFIL', el:'ΠΡΟΦΙΛ', ms:'PROFIL', fa:'پروفایل' },
    'info.money':         { en:'MONEY', fr:'ARGENT', es:'DINERO', de:'GELD', pt:'DINHEIRO', ru:'ДЕНЬГИ', 'zh-hans':'金钱', 'zh-hant':'金錢', ja:'お金', ko:'돈', ar:'المال', hi:'पैसे', it:'DENARO', nl:'GELD', pl:'PIENIĄDZE', tr:'PARA', id:'UANG', vi:'TIỀN', th:'เงิน', uk:'ГРОШІ', sv:'PENGAR', da:'PENGE', fi:'RAHA', no:'PENGER', cs:'PENÍZE', hu:'PÉNZ', ro:'BANI', el:'ΧΡΉΜΑΤΑ', ms:'WANG', fa:'پول' },
    'info.slots':         { en:'Car Slots', fr:'Emplacements voiture', es:'Ranuras de coche', de:'Autostellplätze', pt:'Slots de carro', ru:'Слоты машин', 'zh-hans':'车位', 'zh-hant':'車位', ja:'カースロット', ko:'자동차 슬롯', ar:'فتحات السيارات', hi:'कार स्लॉट', it:'Slot auto', nl:'Autoplaatsen', pl:'Miejsca na samochody', tr:'Araba yuvaları', id:'Slot mobil', vi:'Ô xe', th:'ช่องรถ', uk:'Слоти авто', sv:'Bilplatser', da:'Bilpladser', fi:'Autopaikat', no:'Bilplasser', cs:'Místa pro auta', hu:'Autóhelyek', ro:'Locuri mașini', el:'Θέσεις αυτοκινήτων', ms:'Slot kereta', fa:'جایگاه‌های ماشین' },
    'info.header':        { en:'HEADER', fr:'EN-TÊTE', es:'CABECERA', de:'KOPFZEILE', pt:'CABEÇALHO', ru:'ЗАГОЛОВОК', 'zh-hans':'文件头', 'zh-hant':'檔頭', ja:'ヘッダー', ko:'헤더', ar:'الترويسة', hi:'हेडर', it:'INTESTAZIONE', nl:'HEADER', pl:'NAGŁÓWEK', tr:'BAŞLIK', id:'HEADER', vi:'TIÊU ĐỀ', th:'ส่วนหัว', uk:'ЗАГОЛОВОК', sv:'HEADER', da:'HEADER', fi:'OTSIKKO', no:'HEADER', cs:'ZÁHLAVÍ', hu:'FEJLÉC', ro:'ANTET', el:'ΚΕΦΑΛΊΔΑ', ms:'PENGEPALA', fa:'سربرگ' },
    'info.size':          { en:'SIZE', fr:'TAILLE', es:'TAMAÑO', de:'GRÖSSE', pt:'TAMANHO', ru:'РАЗМЕР', 'zh-hans':'大小', 'zh-hant':'大小', ja:'サイズ', ko:'크기', ar:'الحجم', hi:'आकार', it:'DIMENSIONE', nl:'GROOTTE', pl:'ROZMIAR', tr:'BOYUT', id:'UKURAN', vi:'KÍCH THƯỚC', th:'ขนาด', uk:'РОЗМІР', sv:'STORLEK', da:'STØRRELSE', fi:'KOKO', no:'STØRRELSE', cs:'VELIKOST', hu:'MÉRET', ro:'DIMENSIUNE', el:'ΜΕΓΕΘΟΣ', ms:'SAIZ', fa:'اندازه' },
    'info.valid':         { en:'VALID ✓', fr:'VALIDE ✓', es:'VÁLIDO ✓', de:'GÜLTIG ✓', pt:'VÁLIDO ✓', ru:'ВЕРНЫЙ ✓', 'zh-hans':'有效 ✓', 'zh-hant':'有效 ✓', ja:'有効 ✓', ko:'유효 ✓', ar:'صالح ✓', hi:'मान्य ✓', it:'VALIDO ✓', nl:'GELDIG ✓', pl:'PRAWIDŁOWY ✓', tr:'GEÇERLİ ✓', id:'VALID ✓', vi:'HỢP LỆ ✓', th:'ถูกต้อง ✓', uk:'ДІЙСНИЙ ✓', sv:'GILTIG ✓', da:'GYLDIG ✓', fi:'KELVOLLINEN ✓', no:'GYLDIG ✓', cs:'PLATNÝ ✓', hu:'ÉRVÉNYES ✓', ro:'VALID ✓', el:'ΕΓΚΥΡΟ ✓', ms:'SAH ✓', fa:'معتبر ✓' },
    'info.invalid':       { en:'INVALID ✗', fr:'INVALIDE ✗', es:'INVÁLIDO ✗', de:'UNGÜLTIG ✗', pt:'INVÁLIDO ✗', ru:'НЕВЕРНЫЙ ✗', 'zh-hans':'无效 ✗', 'zh-hant':'無效 ✗', ja:'無効 ✗', ko:'유효하지 않음 ✗', ar:'غير صالح ✗', hi:'अमान्य ✗', it:'NON VALIDO ✗', nl:'ONGELDIG ✗', pl:'NIEPRAWIDŁOWY ✗', tr:'GEÇERSİZ ✗', id:'TIDAK VALID ✗', vi:'KHÔNG HỢP LỆ ✗', th:'ไม่ถูกต้อง ✗', uk:'НЕДІЙСНИЙ ✗', sv:'OGILTIG ✗', da:'UGYLDIG ✗', fi:'VIRHEELLINEN ✗', no:'UGYLDIG ✗', cs:'NEPLATNÝ ✗', hu:'ÉRVÉNYTELEN ✗', ro:'INVALID ✗', el:'ΑΚΥΡΟ ✗', ms:'TIDAK SAH ✗', fa:'نامعتبر ✗' },

    /* ── Editor — Sections ───────────────────────────────── */
    'section.profile':    { en:'Profile', fr:'Profil', es:'Perfil', de:'Profil', pt:'Perfil', ru:'Профиль', 'zh-hans':'档案', 'zh-hant':'檔案', ja:'プロフィール', ko:'프로필', ar:'الملف الشخصي', hi:'प्रोफ़ाइल', it:'Profilo', nl:'Profiel', pl:'Profil', tr:'Profil', id:'Profil', vi:'Hồ sơ', th:'โปรไฟล์', uk:'Профіль', sv:'Profil', da:'Profil', fi:'Profiili', no:'Profil', cs:'Profil', hu:'Profil', ro:'Profil', el:'Προφίλ', ms:'Profil', fa:'پروفایل' },
    'section.money':      { en:'MONEY', fr:'ARGENT', es:'DINERO', de:'GELD', pt:'DINHEIRO', ru:'ДЕНЬГИ', 'zh-hans':'金钱', 'zh-hant':'金錢', ja:'お金', ko:'돈', ar:'المال', hi:'पैसे', it:'DENARO', nl:'GELD', pl:'PIENIĄDZE', tr:'PARA', id:'UANG', vi:'TIỀN', th:'เงิน', uk:'ГРОШІ', sv:'PENGAR', da:'PENGE', fi:'RAHA', no:'PENGER', cs:'PENÍZE', hu:'PÉNZ', ro:'BANI', el:'ΧΡΉΜΑΤΑ', ms:'WANG', fa:'پول' },
    'section.car_slots':  { en:'CAR SLOTS', fr:'EMPLACEMENTS VOITURE', es:'RANURAS DE COCHE', de:'AUTOSTELLPLÄTZE', pt:'SLOTS DE CARRO', ru:'СЛОТЫ МАШИН', 'zh-hans':'车位', 'zh-hant':'車位', ja:'カースロット', ko:'자동차 슬롯', ar:'فتحات السيارات', hi:'कार स्लॉट', it:'SLOT AUTO', nl:'AUTOPLAATSEN', pl:'MIEJSCA NA SAMOCHODY', tr:'ARABA YUVASI', id:'SLOT MOBIL', vi:'Ô XE', th:'ช่องรถ', uk:'СЛОТИ АВТО', sv:'BILPLATSER', da:'BILPLADSER', fi:'AUTOPAIKAT', no:'BILPLASSER', cs:'MÍSTA PRO AUTA', hu:'AUTÓHELYEK', ro:'LOCURI MAȘINI', el:'ΘΕΣΕΙΣ ΑΥΤΟΚΙΝΗΤΩΝ', ms:'SLOT KERETA', fa:'جایگاه‌های ماشین' },
    'section.cheats':     { en:'Cheats', fr:'Triches', es:'Trucos', de:'Cheats', pt:'Trapaças', ru:'Читы', 'zh-hans':'作弊', 'zh-hant':'作弊', ja:'チート', ko:'치트', ar:'الغش', hi:'चीट्स', it:'Trucchi', nl:'Cheats', pl:'Cheaty', tr:'Hileler', id:'Cheat', vi:'Cheat', th:'ชีท', uk:'Чити', sv:'Fusk', da:'Snyd', fi:'Huijauskoodit', no:'Juksekoder', cs:'Cheaty', hu:'Csalások', ro:'Cheat-uri', el:'Cheat', ms:'Cheat', fa:'تقلب' },
    'section.clone':      { en:'Clone Save', fr:'Cloner la sauvegarde', es:'Clonar guardado', de:'Spielstand klonen', pt:'Clonar save', ru:'Клонировать сохранение', 'zh-hans':'克隆存档', 'zh-hant':'複製存檔', ja:'セーブをクローン', ko:'세이브 복제', ar:'استنساخ الحفظ', hi:'सेव क्लोन करें', it:'Clona salvataggio', nl:'Save klonen', pl:'Klonuj zapis', tr:'Kaydı klonla', id:'Klon simpanan', vi:'Nhân bản lưu', th:'โคลนเซฟ', uk:'Клонувати збереження', sv:'Klona sparfil', da:'Klon gemfil', fi:'Kloonaa tallennus', no:'Klon lagring', cs:'Klonovat uloženou hru', hu:'Mentés klónozása', ro:'Clonează salvarea', el:'Κλωνοποίηση αποθήκευσης', ms:'Klon simpanan', fa:'کلون ذخیره' },
    'section.create':     { en:'Create New Profile', fr:'Créer un nouveau profil', es:'Crear nuevo perfil', de:'Neues Profil erstellen', pt:'Criar novo perfil', ru:'Создать новый профиль', 'zh-hans':'创建新档案', 'zh-hant':'建立新檔案', ja:'新しいプロフィールを作成', ko:'새 프로필 만들기', ar:'إنشاء ملف جديد', hi:'नया प्रोफाइल बनाएं', it:'Crea nuovo profilo', nl:'Nieuw profiel aanmaken', pl:'Utwórz nowy profil', tr:'Yeni profil oluştur', id:'Buat profil baru', vi:'Tạo hồ sơ mới', th:'สร้างโปรไฟล์ใหม่', uk:'Створити новий профіль', sv:'Skapa ny profil', da:'Opret ny profil', fi:'Luo uusi profiili', no:'Opprett ny profil', cs:'Vytvořit nový profil', hu:'Új profil létrehozása', ro:'Creați un profil nou', el:'Δημιουργία νέου προφίλ', ms:'Cipta profil baharu', fa:'ایجاد پروفایل جدید' },

    /* ── Editor — Labels & Hints ─────────────────────────── */
    'label.name_hint':    { en:'1–7 alphanumeric', fr:'1–7 caractères alphanumériques', es:'1–7 alfanumérico', de:'1–7 alphanumerisch', pt:'1–7 alfanumérico', ru:'1–7 буквенно-цифровых', 'zh-hans':'1–7位字母数字', 'zh-hant':'1–7位字母數字', ja:'1〜7の英数字', ko:'1~7 영숫자', ar:'١–٧ حرف أو رقم', hi:'1–7 अल्फ़ान्यूमेरिक', it:'1–7 alfanumerico', nl:'1–7 alfanumeriek', pl:'1–7 znaków alfanumerycznych', tr:'1–7 alfanümerik', id:'1–7 alfanumerik', vi:'1–7 ký tự chữ số', th:'1–7 อักขระตัวอักษรและตัวเลข', uk:'1–7 буквено-цифрових', sv:'1–7 alfanumeriska', da:'1–7 alfanumeriske', fi:'1–7 aakkosnumeerista', no:'1–7 alfanumeriske', cs:'1–7 alfanumerických', hu:'1–7 alfanumerikus', ro:'1–7 alfanumerice', el:'1–7 αλφαριθμητικά', ms:'1–7 alfanumerik', fa:'۱–۷ حرف یا عدد' },
    'label.max_chars':    { en:'max 7 chars, alphanumeric', fr:'max 7 caractères, alphanumérique', es:'máx. 7 caracteres alfanuméricos', de:'max. 7 Zeichen, alphanumerisch', pt:'máx. 7 caracteres alfanuméricos', ru:'максимум 7 знаков, буквы и цифры', 'zh-hans':'最多7个字母数字字符', 'zh-hant':'最多7個字母數字字元', ja:'最大7文字の英数字', ko:'최대 7자 영숫자', ar:'حد أقصى ٧ أحرف أو أرقام', hi:'अधिकतम 7 अक्षर, अल्फ़ान्यूमेरिक', it:'max 7 caratteri alfanumerici', nl:'max 7 tekens, alfanumeriek', pl:'maks. 7 znaków alfanumerycznych', tr:'maks. 7 karakter, alfanümerik', id:'maks. 7 karakter, alfanumerik', vi:'tối đa 7 ký tự chữ số', th:'สูงสุด 7 ตัวอักษรหรือตัวเลข', uk:'максимум 7 символів, буквено-цифрових', sv:'max 7 tecken, alfanumeriska', da:'maks. 7 tegn, alfanumeriske', fi:'enintään 7 merkkiä, aakkosnumeerisia', no:'maks. 7 tegn, alfanumeriske', cs:'max. 7 znaků, alfanumerických', hu:'max. 7 alfanumerikus karakter', ro:'max. 7 caractere alfanumerice', el:'μέγ. 7 αλφαριθμητικά χαρακτήρα', ms:'maks. 7 aksara alfanumerik', fa:'حداکثر ۷ کاراکتر حرف یا عدد' },
    'label.money_range':  { en:'(0 – 2,147,483,647)', fr:'(0 – 2 147 483 647)', es:'(0 – 2.147.483.647)', de:'(0 – 2.147.483.647)', pt:'(0 – 2.147.483.647)', ru:'(0 – 2 147 483 647)', 'zh-hans':'(0 – 2,147,483,647)', 'zh-hant':'(0 – 2,147,483,647)', ja:'(0 ～ 2,147,483,647)', ko:'(0 ~ 2,147,483,647)', ar:'(٠ – ٢٬١٤٧٬٤٨٣٬٦٤٧)', hi:'(0 – 2,147,483,647)', it:'(0 – 2.147.483.647)', nl:'(0 – 2.147.483.647)', pl:'(0 – 2 147 483 647)', tr:'(0 – 2.147.483.647)', id:'(0 – 2.147.483.647)', vi:'(0 – 2.147.483.647)', th:'(0 – 2,147,483,647)', uk:'(0 – 2 147 483 647)', sv:'(0 – 2 147 483 647)', da:'(0 – 2.147.483.647)', fi:'(0 – 2 147 483 647)', no:'(0 – 2 147 483 647)', cs:'(0 – 2 147 483 647)', hu:'(0 – 2 147 483 647)', ro:'(0 – 2.147.483.647)', el:'(0 – 2.147.483.647)', ms:'(0 – 2,147,483,647)', fa:'(۰ – ۲٬۱۴۷٬۴۸۳٬۶۴۷)' },
    'label.max_money':    { en:'max 2,147,483,647', fr:'max 2 147 483 647', es:'máx. 2.147.483.647', de:'max. 2.147.483.647', pt:'máx. 2.147.483.647', ru:'максимум 2 147 483 647', 'zh-hans':'最大 2,147,483,647', 'zh-hant':'最大 2,147,483,647', ja:'最大 2,147,483,647', ko:'최대 2,147,483,647', ar:'الحد الأقصى ٢٬١٤٧٬٤٨٣٬٦٤٧', hi:'अधिकतम 2,147,483,647', it:'max 2.147.483.647', nl:'max 2.147.483.647', pl:'maks. 2 147 483 647', tr:'maks. 2.147.483.647', id:'maks. 2.147.483.647', vi:'tối đa 2.147.483.647', th:'สูงสุด 2,147,483,647', uk:'максимум 2 147 483 647', sv:'max 2 147 483 647', da:'maks. 2.147.483.647', fi:'enintään 2 147 483 647', no:'maks. 2 147 483 647', cs:'max. 2 147 483 647', hu:'max. 2 147 483 647', ro:'max. 2.147.483.647', el:'μέγ. 2.147.483.647', ms:'maks. 2,147,483,647', fa:'حداکثر ۲٬۱۴۷٬۴۸۳٬۶۴۷' },
    'label.perf_hint':    { en:'MAX fills all performance stats. NIL zeroes them.', fr:'MAX remplit toutes les stats. NIL les remet à zéro.', es:'MAX rellena las estadísticas. NIL las pone a cero.', de:'MAX füllt alle Stats. NIL setzt sie auf Null.', pt:'MAX preenche todas as estatísticas. NIL as zera.', ru:'MAX заполняет все характеристики. NIL обнуляет их.', 'zh-hans':'MAX 填满所有性能值，NIL 将其清零。', 'zh-hant':'MAX 填滿所有性能值，NIL 將其清零。', ja:'MAXはすべての性能値を最大に、NILはゼロにします。', ko:'MAX는 모든 성능 수치를 채우고, NIL은 초기화합니다.', ar:'MAX يملأ جميع إحصائيات الأداء. NIL يجعلها صفراً.', hi:'MAX सभी परफॉर्मेंस स्टैट्स भरता है। NIL उन्हें शून्य करता है।', it:'MAX riempie tutte le statistiche. NIL le azzera.', nl:'MAX vult alle statistieken. NIL maakt ze nul.', pl:'MAX wypełnia wszystkie statystyki. NIL zeruje je.', tr:'MAX tüm performans değerlerini doldurur. NIL sıfırlar.', id:'MAX mengisi semua statistik. NIL menolkan semua.', vi:'MAX điền tất cả chỉ số. NIL đặt về không.', th:'MAX เติมสถิติทั้งหมด NIL ทำให้เป็นศูนย์', uk:'MAX заповнює всі характеристики. NIL обнуляє їх.', sv:'MAX fyller alla prestandavärden. NIL nollställer dem.', da:'MAX udfylder alle statistikker. NIL nulstiller dem.', fi:'MAX täyttää kaikki tilastot. NIL nollaa ne.', no:'MAX fyller alle statistikker. NIL nullstiller dem.', cs:'MAX vyplní všechny statistiky. NIL je vynuluje.', hu:'MAX kitölti az összes statisztikát. NIL nullázza őket.', ro:'MAX umple toate statisticile. NIL le anulează.', el:'Το MAX γεμίζει όλες τις στατιστικές. Το NIL τις μηδενίζει.', ms:'MAX mengisi semua statistik. NIL menolkan semua.', fa:'MAX همه آمارها را پر می‌کند. NIL آن‌ها را صفر می‌کند.' },
    'label.clone_hint':   { en:'Copy the loaded save under a new profile name.', fr:'Copiez la sauvegarde chargée sous un nouveau nom de profil.', es:'Copia el guardado cargado con un nuevo nombre de perfil.', de:'Kopiert den geladenen Spielstand unter einem neuen Profilnamen.', pt:'Copia o save carregado com um novo nome de perfil.', ru:'Копирует загруженное сохранение под новым именем профиля.', 'zh-hans':'用新档案名称复制已加载的存档。', 'zh-hant':'以新檔案名稱複製已載入的存檔。', ja:'読み込んだセーブを新しいプロフィール名でコピーします。', ko:'불러온 세이브를 새 프로필 이름으로 복사합니다.', ar:'انسخ الحفظ المحمّل باسم ملف شخصي جديد.', hi:'लोड किए गए सेव को नए प्रोफाइल नाम से कॉपी करें।', it:'Copia il salvataggio caricato con un nuovo nome profilo.', nl:'Kopieer de geladen save onder een nieuwe profielnaam.', pl:'Skopiuj wczytany zapis pod nową nazwą profilu.', tr:'Yüklenen kaydı yeni bir profil adıyla kopyala.', id:'Salin simpanan yang dimuat dengan nama profil baru.', vi:'Sao chép bản lưu đã tải với tên hồ sơ mới.', th:'คัดลอกเซฟที่โหลดไว้ภายใต้ชื่อโปรไฟล์ใหม่', uk:'Скопіюйте завантажене збереження з новим ім\'ям профілю.', sv:'Kopiera den inladdade sparfilen med ett nytt profilnamn.', da:'Kopiér den indlæste gemfil med et nyt profilnavn.', fi:'Kopioi ladattu tallennus uudella profiililla.', no:'Kopier den lastede lagringen med et nytt profilnavn.', cs:'Zkopírujte načtenou uloženou hru pod novým názvem profilu.', hu:'Másolja a betöltött mentést új profilnéven.', ro:'Copiați salvarea încărcată cu un nou nume de profil.', el:'Αντιγράψτε την αποθήκευση με νέο όνομα προφίλ.', ms:'Salin simpanan yang dimuatkan dengan nama profil baharu.', fa:'ذخیره بارگذاری شده را با نام پروفایل جدید کپی کنید.' },
    'label.create_hint':  { en:'Generates a fresh NFSU2 save file ready to play.', fr:'Génère un nouveau fichier de sauvegarde NFSU2 prêt à jouer.', es:'Genera un nuevo archivo de guardado NFSU2 listo para jugar.', de:'Erzeugt eine neue NFSU2-Speicherdatei, die sofort spielbereit ist.', pt:'Gera um novo arquivo de save do NFSU2 pronto para jogar.', ru:'Создаёт новый файл сохранения NFSU2, готовый к игре.', 'zh-hans':'生成一个全新的NFSU2存档文件，可直接游玩。', 'zh-hant':'生成一個全新的NFSU2存檔，可立即遊玩。', ja:'すぐにプレイできる新しいNFSU2セーブファイルを生成します。', ko:'바로 플레이할 수 있는 새 NFSU2 세이브 파일을 생성합니다.', ar:'ينشئ ملف حفظ NFSU2 جديداً جاهزاً للعب.', hi:'एक नया NFSU2 सेव फ़ाइल तैयार करता है जो खेलने के लिए तैयार है।', it:'Genera un nuovo file di salvataggio NFSU2 pronto per giocare.', nl:'Genereert een nieuw NFSU2-savebestand, klaar om te spelen.', pl:'Generuje nowy plik zapisu NFSU2 gotowy do gry.', tr:'Oynamaya hazır yeni bir NFSU2 kayıt dosyası oluşturur.', id:'Membuat file simpanan NFSU2 baru yang siap dimainkan.', vi:'Tạo tệp lưu NFSU2 mới sẵn sàng để chơi.', th:'สร้างไฟล์เซฟ NFSU2 ใหม่ที่พร้อมเล่น', uk:'Генерує новий файл збереження NFSU2, готовий до гри.', sv:'Genererar en ny NFSU2-sparfil redo att spela.', da:'Genererer en ny NFSU2-gemfil klar til at spille.', fi:'Luo uuden NFSU2-tallennustiedoston, joka on valmis pelattavaksi.', no:'Genererer en ny NFSU2-lagringsfil klar til å spille.', cs:'Vygeneruje nový soubor uložené hry NFSU2 připravený k hraní.', hu:'Új, játékra kész NFSU2 mentésfájlt hoz létre.', ro:'Generează un nou fișier de salvare NFSU2 gata de jucat.', el:'Δημιουργεί νέο αρχείο αποθήκευσης NFSU2 έτοιμο για παιχνίδι.', ms:'Menjana fail simpanan NFSU2 baharu yang sedia dimainkan.', fa:'یک فایل ذخیره جدید NFSU2 آماده بازی تولید می‌کند.' },
    'label.car_hint':     { en:'(optional — default is Peugeot 206)', fr:'(facultatif — par défaut : Peugeot 206)', es:'(opcional — por defecto: Peugeot 206)', de:'(optional — Standard: Peugeot 206)', pt:'(opcional — padrão: Peugeot 206)', ru:'(необязательно — по умолчанию Peugeot 206)', 'zh-hans':'（可选 — 默认: Peugeot 206）', 'zh-hant':'（可選 — 預設: Peugeot 206）', ja:'（任意 — デフォルト: Peugeot 206）', ko:'(선택 — 기본값: Peugeot 206)', ar:'(اختياري — الافتراضي: بيجو 206)', hi:'(वैकल्पिक — डिफ़ॉल्ट: Peugeot 206)', it:'(facoltativo — predefinito: Peugeot 206)', nl:'(optioneel — standaard: Peugeot 206)', pl:'(opcjonalne — domyślnie: Peugeot 206)', tr:'(isteğe bağlı — varsayılan: Peugeot 206)', id:'(opsional — default: Peugeot 206)', vi:'(tuỳ chọn — mặc định: Peugeot 206)', th:'(ไม่บังคับ — ค่าเริ่มต้น: Peugeot 206)', uk:'(необов\'язково — за замовчуванням: Peugeot 206)', sv:'(valfritt — standard: Peugeot 206)', da:'(valgfrit — standard: Peugeot 206)', fi:'(valinnainen — oletus: Peugeot 206)', no:'(valgfritt — standard: Peugeot 206)', cs:'(volitelné — výchozí: Peugeot 206)', hu:'(opcionális — alapértelmezett: Peugeot 206)', ro:'(opțional — implicit: Peugeot 206)', el:'(προαιρετικό — προεπιλογή: Peugeot 206)', ms:'(pilihan — lalai: Peugeot 206)', fa:'(اختیاری — پیش‌فرض: Peugeot 206)' },

    /* ── Editor — Buttons ────────────────────────────────── */
    'btn.max_money':      { en:'Max Money', fr:'Argent max', es:'Dinero máximo', de:'Max Geld', pt:'Dinheiro máximo', ru:'Макс деньги', 'zh-hans':'最大金钱', 'zh-hant':'最大金錢', ja:'金額最大化', ko:'최대 돈', ar:'أقصى مال', hi:'अधिकतम पैसे', it:'Soldi massimi', nl:'Max geld', pl:'Maks pieniędzy', tr:'Maks para', id:'Uang maks', vi:'Tiền tối đa', th:'เงินสูงสุด', uk:'Максимум грошей', sv:'Max pengar', da:'Maks penge', fi:'Maks rahat', no:'Maks penger', cs:'Max peněz', hu:'Max pénz', ro:'Bani maximi', el:'Μέγ. χρήματα', ms:'Wang maks', fa:'حداکثر پول' },
    'btn.unlock_slots':   { en:'Unlock All Car Slots', fr:'Déverrouiller tous les emplacements', es:'Desbloquear todas las ranuras', de:'Alle Autostellplätze freischalten', pt:'Desbloquear todos os slots', ru:'Разблокировать все слоты', 'zh-hans':'解锁所有车位', 'zh-hant':'解鎖所有車位', ja:'全カースロットを解放', ko:'모든 자동차 슬롯 해제', ar:'فتح جميع فتحات السيارات', hi:'सभी कार स्लॉट अनलॉक करें', it:'Sblocca tutti gli slot auto', nl:'Alle autoplaatsen ontgrendelen', pl:'Odblokuj wszystkie miejsca na auta', tr:'Tüm araba yuvalarını aç', id:'Buka semua slot mobil', vi:'Mở khóa tất cả ô xe', th:'ปลดล็อคช่องรถทั้งหมด', uk:'Розблокувати всі слоти авто', sv:'Lås upp alla bilplatser', da:'Lås alle bilpladser op', fi:'Avaa kaikki autopaikat', no:'Lås opp alle bilplasser', cs:'Odemkněte všechna místa pro auta', hu:'Az összes autóhely feloldása', ro:'Deblochează toate locurile de mașini', el:'Ξεκλείδωμα όλων των θέσεων', ms:'Buka kunci semua slot kereta', fa:'باز کردن همه جایگاه‌های ماشین' },
    'btn.unlock_parts':   { en:'Unlock All Parts', fr:'Déverrouiller toutes les pièces', es:'Desbloquear todas las piezas', de:'Alle Teile freischalten', pt:'Desbloquear todas as peças', ru:'Разблокировать все детали', 'zh-hans':'解锁所有零件', 'zh-hant':'解鎖所有零件', ja:'全パーツを解放', ko:'모든 파츠 해제', ar:'فتح جميع الأجزاء', hi:'सभी पार्ट्स अनलॉक करें', it:'Sblocca tutti i pezzi', nl:'Alle onderdelen ontgrendelen', pl:'Odblokuj wszystkie części', tr:'Tüm parçaları aç', id:'Buka semua suku cadang', vi:'Mở khóa tất cả phụ tùng', th:'ปลดล็อคอะไหล่ทั้งหมด', uk:'Розблокувати всі деталі', sv:'Lås upp alla delar', da:'Lås alle dele op', fi:'Avaa kaikki osat', no:'Lås opp alle deler', cs:'Odemkněte všechny části', hu:'Az összes alkatrész feloldása', ro:'Deblochează toate piesele', el:'Ξεκλείδωμα όλων των εξαρτημάτων', ms:'Buka kunci semua bahagian', fa:'باز کردن همه قطعات' },
    'btn.create_download':{ en:'Create & Download', fr:'Créer & Télécharger', es:'Crear y Descargar', de:'Erstellen & Herunterladen', pt:'Criar & Baixar', ru:'Создать и скачать', 'zh-hans':'创建并下载', 'zh-hant':'建立並下載', ja:'作成してダウンロード', ko:'만들기 & 다운로드', ar:'إنشاء وتنزيل', hi:'बनाएं और डाउनलोड करें', it:'Crea e Scarica', nl:'Maak & Download', pl:'Utwórz i pobierz', tr:'Oluştur & İndir', id:'Buat & Unduh', vi:'Tạo & Tải xuống', th:'สร้างและดาวน์โหลด', uk:'Створити та завантажити', sv:'Skapa & Ladda ner', da:'Opret & Download', fi:'Luo & Lataa', no:'Opprett & Last ned', cs:'Vytvořit & Stáhnout', hu:'Létrehozás & Letöltés', ro:'Creează & Descarcă', el:'Δημιουργία & Λήψη', ms:'Cipta & Muat turun', fa:'ایجاد و دانلود' },
    'btn.max':            { en:'MAX', fr:'MAX', es:'MAX', de:'MAX', pt:'MAX', ru:'МАКС', 'zh-hans':'MAX', 'zh-hant':'MAX', ja:'MAX', ko:'MAX', ar:'الحد الأقصى', hi:'MAX', it:'MAX', nl:'MAX', pl:'MAX', tr:'MAX', id:'MAX', vi:'MAX', th:'MAX', uk:'MAX', sv:'MAX', da:'MAX', fi:'MAX', no:'MAX', cs:'MAX', hu:'MAX', ro:'MAX', el:'MAX', ms:'MAX', fa:'MAX' },
    'btn.nil':            { en:'NIL', fr:'NIL', es:'NIL', de:'NIL', pt:'NIL', ru:'НОЛЬ', 'zh-hans':'NIL', 'zh-hant':'NIL', ja:'NIL', ko:'NIL', ar:'صفر', hi:'NIL', it:'NIL', nl:'NIL', pl:'NIL', tr:'NIL', id:'NIL', vi:'NIL', th:'NIL', uk:'NIL', sv:'NIL', da:'NIL', fi:'NIL', no:'NIL', cs:'NIL', hu:'NIL', ro:'NIL', el:'NIL', ms:'NIL', fa:'NIL' },
    'btn.unlock_slot':    { en:'Unlock this slot', fr:'Déverrouiller cet emplacement', es:'Desbloquear esta ranura', de:'Diesen Stellplatz freischalten', pt:'Desbloquear este slot', ru:'Разблокировать этот слот', 'zh-hans':'解锁此车位', 'zh-hant':'解鎖此車位', ja:'このスロットを解放', ko:'이 슬롯 해제', ar:'فتح هذه الفتحة', hi:'यह स्लॉट अनलॉक करें', it:'Sblocca questo slot', nl:'Ontgrendel dit slot', pl:'Odblokuj to miejsce', tr:'Bu yuvayı aç', id:'Buka slot ini', vi:'Mở khóa ô này', th:'ปลดล็อคช่องนี้', uk:'Розблокувати цей слот', sv:'Lås upp denna plats', da:'Lås denne plads op', fi:'Avaa tämä paikka', no:'Lås opp denne plassen', cs:'Odemkněte toto místo', hu:'Nyissa fel ezt a helyet', ro:'Deblochează acest slot', el:'Ξεκλείδωμα αυτής της θέσης', ms:'Buka kunci slot ini', fa:'باز کردن این جایگاه' },

    /* ── Editor — Slot states ────────────────────────────── */
    'slot.in_use':        { en:'IN USE', fr:'EN COURS', es:'EN USO', de:'BELEGT', pt:'EM USO', ru:'ИСПОЛЬЗУЕТСЯ', 'zh-hans':'已使用', 'zh-hant':'已使用', ja:'使用中', ko:'사용 중', ar:'قيد الاستخدام', hi:'उपयोग में', it:'IN USO', nl:'IN GEBRUIK', pl:'UŻYWANE', tr:'KULLANILIYOR', id:'DIGUNAKAN', vi:'ĐANG DÙNG', th:'กำลังใช้', uk:'ВИКОРИСТОВУЄТЬСЯ', sv:'ANVÄNDS', da:'I BRUG', fi:'KÄYTÖSSÄ', no:'I BRUK', cs:'POUŽÍVÁ SE', hu:'HASZNÁLATBAN', ro:'ÎN UTILIZARE', el:'ΣΕ ΧΡΗΣΗ', ms:'SEDANG DIGUNAKAN', fa:'در حال استفاده' },
    'slot.empty':         { en:'EMPTY', fr:'VIDE', es:'VACÍO', de:'LEER', pt:'VAZIO', ru:'ПУСТО', 'zh-hans':'空', 'zh-hant':'空', ja:'空', ko:'비어있음', ar:'فارغ', hi:'खाली', it:'VUOTO', nl:'LEEG', pl:'PUSTE', tr:'BOŞ', id:'KOSONG', vi:'TRỐNG', th:'ว่าง', uk:'ПОРОЖНІЙ', sv:'TOM', da:'TOM', fi:'TYHJÄ', no:'TOM', cs:'PRÁZDNÉ', hu:'ÜRES', ro:'GOL', el:'ΚΕΝΟ', ms:'KOSONG', fa:'خالی' },

    /* ── Editor — Toast messages ─────────────────────────── */
    'toast.slot_maxed':       { en:'Slot {n} performance maxed.', fr:'Performance de l\'emplacement {n} maximisée.', es:'Rendimiento de la ranura {n} al máximo.', de:'Leistung von Slot {n} maximiert.', pt:'Performance do slot {n} no máximo.', ru:'Характеристики слота {n} максимизированы.', 'zh-hans':'车位 {n} 性能已最大化。', 'zh-hant':'車位 {n} 性能已最大化。', ja:'スロット {n} の性能を最大化しました。', ko:'슬롯 {n} 성능이 최대화되었습니다.', ar:'تم رفع أداء الفتحة {n} إلى الحد الأقصى.', hi:'स्लॉट {n} की परफॉर्मेंस अधिकतम कर दी गई।', it:'Prestazioni dello slot {n} al massimo.', nl:'Prestaties van slot {n} gemaximaliseerd.', pl:'Wydajność miejsca {n} zmaksymalizowana.', tr:'Yuva {n} performansı maksimize edildi.', id:'Performa slot {n} dimaksimalkan.', vi:'Hiệu suất ô {n} đã tối đa.', th:'สล็อต {n} ประสิทธิภาพสูงสุดแล้ว', uk:'Характеристики слота {n} максимізовано.', sv:'Slot {n} prestanda maximerad.', da:'Slot {n} ydeevne maksimeret.', fi:'Paikka {n} suorituskyky maksimoitu.', no:'Plass {n} ytelse maksimert.', cs:'Výkon místa {n} maximalizován.', hu:'A(z) {n}. hely teljesítménye maximalizálva.', ro:'Performanța slotului {n} maximizată.', el:'Η απόδοση της θέσης {n} μεγιστοποιήθηκε.', ms:'Prestasi slot {n} dimaksimumkan.', fa:'عملکرد جایگاه {n} به حداکثر رسید.' },
    'toast.slot_zeroed':      { en:'Slot {n} performance zeroed.', fr:'Performance de l\'emplacement {n} remise à zéro.', es:'Rendimiento de la ranura {n} puesto a cero.', de:'Leistung von Slot {n} auf Null gesetzt.', pt:'Performance do slot {n} zerada.', ru:'Характеристики слота {n} обнулены.', 'zh-hans':'车位 {n} 性能已清零。', 'zh-hant':'車位 {n} 性能已清零。', ja:'スロット {n} の性能をゼロにしました。', ko:'슬롯 {n} 성능이 초기화되었습니다.', ar:'تم تصفير أداء الفتحة {n}.', hi:'स्लॉट {n} की परफॉर्मेंस शून्य कर दी गई।', it:'Prestazioni dello slot {n} azzerate.', nl:'Prestaties van slot {n} op nul gezet.', pl:'Wydajność miejsca {n} wyzerowana.', tr:'Yuva {n} performansı sıfırlandı.', id:'Performa slot {n} dinolkan.', vi:'Hiệu suất ô {n} đã về không.', th:'สล็อต {n} ประสิทธิภาพเป็นศูนย์แล้ว', uk:'Характеристики слота {n} обнулено.', sv:'Slot {n} prestanda nollställd.', da:'Slot {n} ydeevne nulstillet.', fi:'Paikka {n} suorituskyky nollattu.', no:'Plass {n} ytelse nullstilt.', cs:'Výkon místa {n} vynulován.', hu:'A(z) {n}. hely teljesítménye nullázva.', ro:'Performanța slotului {n} anulată.', el:'Η απόδοση της θέσης {n} μηδενίστηκε.', ms:'Prestasi slot {n} dinolkan.', fa:'عملکرد جایگاه {n} صفر شد.' },
    'toast.slot_unlocked':    { en:'Slot {n} unlocked.', fr:'Emplacement {n} déverrouillé.', es:'Ranura {n} desbloqueada.', de:'Slot {n} freigeschaltet.', pt:'Slot {n} desbloqueado.', ru:'Слот {n} разблокирован.', 'zh-hans':'车位 {n} 已解锁。', 'zh-hant':'車位 {n} 已解鎖。', ja:'スロット {n} を解放しました。', ko:'슬롯 {n} 잠금 해제되었습니다.', ar:'تم فتح الفتحة {n}.', hi:'स्लॉट {n} अनलॉक हो गया।', it:'Slot {n} sbloccato.', nl:'Slot {n} ontgrendeld.', pl:'Miejsce {n} odblokowane.', tr:'Yuva {n} açıldı.', id:'Slot {n} dibuka.', vi:'Ô {n} đã mở khóa.', th:'สล็อต {n} ถูกปลดล็อคแล้ว', uk:'Слот {n} розблоковано.', sv:'Slot {n} upplåst.', da:'Slot {n} låst op.', fi:'Paikka {n} avattu.', no:'Plass {n} låst opp.', cs:'Místo {n} odemčeno.', hu:'A(z) {n}. hely feloldva.', ro:'Slotul {n} deblocat.', el:'Η θέση {n} ξεκλειδώθηκε.', ms:'Slot {n} dibuka kunci.', fa:'جایگاه {n} باز شد.' },
    'toast.loaded_backup':    { en:'Save loaded. Backup downloaded.', fr:'Sauvegarde chargée. Backup téléchargé.', es:'Guardado cargado. Copia descargada.', de:'Spielstand geladen. Backup heruntergeladen.', pt:'Save carregado. Backup baixado.', ru:'Сохранение загружено. Резервная копия скачана.', 'zh-hans':'存档已加载。备份已下载。', 'zh-hant':'存檔已載入。備份已下載。', ja:'セーブを読み込みました。バックアップをダウンロードしました。', ko:'세이브 불러옴. 백업 다운로드 완료.', ar:'تم تحميل الحفظ. تم تنزيل النسخة الاحتياطية.', hi:'सेव लोड हुआ। बैकअप डाउनलोड हुआ।', it:'Salvataggio caricato. Backup scaricato.', nl:'Save geladen. Backup gedownload.', pl:'Zapis wczytany. Kopia zapasowa pobrana.', tr:'Kayıt yüklendi. Yedek indirildi.', id:'Simpanan dimuat. Cadangan diunduh.', vi:'Đã tải bản lưu. Đã tải bản sao lưu.', th:'โหลดเซฟแล้ว ดาวน์โหลดสำรองแล้ว', uk:'Збереження завантажено. Резервна копія завантажена.', sv:'Sparfil laddad. Backup nedladdad.', da:'Gemfil indlæst. Backup downloadet.', fi:'Tallennus ladattu. Varmuuskopio ladattu.', no:'Lagring lastet inn. Sikkerhetskopi lastet ned.', cs:'Uložená hra načtena. Záloha stažena.', hu:'Mentés betöltve. Biztonsági mentés letöltve.', ro:'Salvare încărcată. Backup descărcat.', el:'Η αποθήκευση φορτώθηκε. Το αντίγραφο ασφαλείας λήφθηκε.', ms:'Simpanan dimuatkan. Sandaran dimuat turun.', fa:'ذخیره بارگذاری شد. پشتیبان دانلود شد.' },
    'toast.loaded':           { en:'Save loaded: {name}', fr:'Sauvegarde chargée : {name}', es:'Guardado cargado: {name}', de:'Spielstand geladen: {name}', pt:'Save carregado: {name}', ru:'Сохранение загружено: {name}', 'zh-hans':'存档已加载：{name}', 'zh-hant':'存檔已載入：{name}', ja:'セーブを読み込みました：{name}', ko:'세이브 불러옴: {name}', ar:'تم تحميل الحفظ: {name}', hi:'सेव लोड हुआ: {name}', it:'Salvataggio caricato: {name}', nl:'Save geladen: {name}', pl:'Zapis wczytany: {name}', tr:'Kayıt yüklendi: {name}', id:'Simpanan dimuat: {name}', vi:'Đã tải bản lưu: {name}', th:'โหลดเซฟแล้ว: {name}', uk:'Збереження завантажено: {name}', sv:'Sparfil laddad: {name}', da:'Gemfil indlæst: {name}', fi:'Tallennus ladattu: {name}', no:'Lagring lastet inn: {name}', cs:'Uložená hra načtena: {name}', hu:'Mentés betöltve: {name}', ro:'Salvare încărcată: {name}', el:'Η αποθήκευση φορτώθηκε: {name}', ms:'Simpanan dimuatkan: {name}', fa:'ذخیره بارگذاری شد: {name}' },
    'toast.err_name':         { en:'Enter a profile name (1–7 alphanumeric).', fr:'Entrez un nom de profil (1–7 caractères alphanumériques).', es:'Ingresa un nombre de perfil (1–7 alfanumérico).', de:'Profilnamen eingeben (1–7 alphanumerisch).', pt:'Digite um nome de perfil (1–7 alfanumérico).', ru:'Введите имя профиля (1–7 буквенно-цифровых символов).', 'zh-hans':'请输入档案名称（1–7位字母数字）。', 'zh-hant':'請輸入檔案名稱（1–7位字母數字）。', ja:'プロフィール名を入力してください（1〜7の英数字）。', ko:'프로필 이름을 입력하세요 (1~7 영숫자).', ar:'أدخل اسم الملف (١–٧ أحرف أو أرقام).', hi:'प्रोफाइल नाम दर्ज करें (1–7 अल्फ़ान्यूमेरिक)।', it:'Inserisci un nome profilo (1–7 alfanumerico).', nl:'Voer een profielnaam in (1–7 alfanumeriek).', pl:'Podaj nazwę profilu (1–7 znaków alfanumerycznych).', tr:'Profil adı gir (1–7 alfanümerik).', id:'Masukkan nama profil (1–7 alfanumerik).', vi:'Nhập tên hồ sơ (1–7 ký tự chữ số).', th:'กรอกชื่อโปรไฟล์ (1–7 ตัวอักษรหรือตัวเลข)', uk:'Введіть ім\'я профілю (1–7 буквено-цифрових символів).', sv:'Ange ett profilnamn (1–7 alfanumeriska).', da:'Indtast et profilnavn (1–7 alfanumeriske).', fi:'Anna profiilinimi (1–7 aakkosnumeerista).', no:'Skriv inn et profilnavn (1–7 alfanumeriske).', cs:'Zadejte název profilu (1–7 alfanumerických znaků).', hu:'Adjon meg profilnevet (1–7 alfanumerikus karakter).', ro:'Introduceți un nume de profil (1–7 alfanumerice).', el:'Εισάγετε όνομα προφίλ (1–7 αλφαριθμητικά).', ms:'Masukkan nama profil (1–7 alfanumerik).', fa:'یک نام پروفایل وارد کنید (۱–۷ حرف یا عدد).' },
    'toast.err_clone_name':   { en:'Enter a new profile name (1–7 alphanumeric).', fr:'Entrez un nouveau nom de profil (1–7 caractères alphanumériques).', es:'Ingresa un nuevo nombre de perfil (1–7 alfanumérico).', de:'Neuen Profilnamen eingeben (1–7 alphanumerisch).', pt:'Digite um novo nome de perfil (1–7 alfanumérico).', ru:'Введите новое имя профиля (1–7 буквенно-цифровых символов).', 'zh-hans':'请输入新档案名称（1–7位字母数字）。', 'zh-hant':'請輸入新檔案名稱（1–7位字母數字）。', ja:'新しいプロフィール名を入力してください（1〜7の英数字）。', ko:'새 프로필 이름을 입력하세요 (1~7 영숫자).', ar:'أدخل اسم ملف جديداً (١–٧ أحرف أو أرقام).', hi:'नया प्रोफाइल नाम दर्ज करें (1–7 अल्फ़ान्यूमेरिक)।', it:'Inserisci un nuovo nome profilo (1–7 alfanumerico).', nl:'Voer een nieuwe profielnaam in (1–7 alfanumeriek).', pl:'Podaj nową nazwę profilu (1–7 znaków alfanumerycznych).', tr:'Yeni profil adı gir (1–7 alfanümerik).', id:'Masukkan nama profil baru (1–7 alfanumerik).', vi:'Nhập tên hồ sơ mới (1–7 ký tự chữ số).', th:'กรอกชื่อโปรไฟล์ใหม่ (1–7 ตัวอักษรหรือตัวเลข)', uk:'Введіть нове ім\'я профілю (1–7 буквено-цифрових символів).', sv:'Ange ett nytt profilnamn (1–7 alfanumeriska).', da:'Indtast et nyt profilnavn (1–7 alfanumeriske).', fi:'Anna uusi profiilinimi (1–7 aakkosnumeerista).', no:'Skriv inn et nytt profilnavn (1–7 alfanumeriske).', cs:'Zadejte nový název profilu (1–7 alfanumerických znaků).', hu:'Adjon meg új profilnevet (1–7 alfanumerikus karakter).', ro:'Introduceți un nou nume de profil (1–7 alfanumerice).', el:'Εισάγετε νέο όνομα προφίλ (1–7 αλφαριθμητικά).', ms:'Masukkan nama profil baharu (1–7 alfanumerik).', fa:'یک نام پروفایل جدید وارد کنید (۱–۷ حرف یا عدد).' },
    'toast.cloned':           { en:'Save cloned as "{name}" and downloaded.', fr:'Sauvegarde clonée sous "{name}" et téléchargée.', es:'Guardado clonado como "{name}" y descargado.', de:'Spielstand als "{name}" geklont und heruntergeladen.', pt:'Save clonado como "{name}" e baixado.', ru:'Сохранение клонировано как "{name}" и скачано.', 'zh-hans':'存档已克隆为"{name}"并下载。', 'zh-hant':'存檔已複製為"{name}"並下載。', ja:'セーブを"{name}"としてクローンしてダウンロードしました。', ko:'세이브가 "{name}"으로 복제되어 다운로드되었습니다.', ar:'تم استنساخ الحفظ كـ"{name}" وتنزيله.', hi:'सेव "{name}" के रूप में क्लोन और डाउनलोड हुआ।', it:'Salvataggio clonato come "{name}" e scaricato.', nl:'Save gekloond als "{name}" en gedownload.', pl:'Zapis sklonowany jako "{name}" i pobrany.', tr:'Kayıt "{name}" olarak klonlandı ve indirildi.', id:'Simpanan dikloning sebagai "{name}" dan diunduh.', vi:'Bản lưu được nhân bản thành "{name}" và đã tải xuống.', th:'เซฟถูกโคลนเป็น "{name}" และดาวน์โหลดแล้ว', uk:'Збереження клоновано як "{name}" та завантажено.', sv:'Sparfil klonad som "{name}" och nedladdad.', da:'Gemfil klonet som "{name}" og downloadet.', fi:'Tallennus kloonattu nimellä "{name}" ja ladattu.', no:'Lagring klonet som "{name}" og lastet ned.', cs:'Uložená hra naklonována jako "{name}" a stažena.', hu:'A mentés "{name}" néven klónozva és letöltve.', ro:'Salvarea clonată ca "{name}" și descărcată.', el:'Η αποθήκευση κλωνοποιήθηκε ως "{name}" και λήφθηκε.', ms:'Simpanan diklonkan sebagai "{name}" dan dimuat turun.', fa:'ذخیره به عنوان "{name}" کلون شد و دانلود شد.' },
    'toast.parts_unlocked':   { en:'All parts unlocked across all slots.', fr:'Toutes les pièces déverrouillées dans tous les emplacements.', es:'Todas las piezas desbloqueadas en todas las ranuras.', de:'Alle Teile in allen Slots freigeschaltet.', pt:'Todas as peças desbloqueadas em todos os slots.', ru:'Все детали разблокированы во всех слотах.', 'zh-hans':'所有车位的所有零件已解锁。', 'zh-hant':'所有車位的所有零件已解鎖。', ja:'全スロットの全パーツを解放しました。', ko:'모든 슬롯의 모든 파츠가 해제되었습니다.', ar:'تم فتح جميع الأجزاء في جميع الفتحات.', hi:'सभी स्लॉट में सभी पार्ट्स अनलॉक हो गए।', it:'Tutti i pezzi sbloccati in tutti gli slot.', nl:'Alle onderdelen in alle slots ontgrendeld.', pl:'Wszystkie części we wszystkich miejscach odblokowane.', tr:'Tüm yuvalardaki tüm parçalar açıldı.', id:'Semua suku cadang di semua slot dibuka.', vi:'Đã mở khóa tất cả phụ tùng ở tất cả ô.', th:'ปลดล็อคอะไหล่ทั้งหมดในทุกช่องแล้ว', uk:'Усі деталі в усіх слотах розблоковано.', sv:'Alla delar upplåsta i alla slots.', da:'Alle dele låst op på tværs af alle slots.', fi:'Kaikki osat avattu kaikissa paikoissa.', no:'Alle deler låst opp i alle plasser.', cs:'Všechny části ve všech místech odemčeny.', hu:'Az összes alkatrész az összes helyen feloldva.', ro:'Toate piesele deblocate în toate sloturile.', el:'Όλα τα εξαρτήματα ξεκλειδώθηκαν σε όλες τις θέσεις.', ms:'Semua bahagian dibuka kunci di semua slot.', fa:'همه قطعات در همه جایگاه‌ها باز شدند.' },
    'toast.slots_unlocked':   { en:'All 5 car slots unlocked.', fr:'Les 5 emplacements voiture déverrouillés.', es:'Las 5 ranuras de coche desbloqueadas.', de:'Alle 5 Autostellplätze freigeschaltet.', pt:'Todos os 5 slots de carro desbloqueados.', ru:'Все 5 слотов машин разблокированы.', 'zh-hans':'全部5个车位已解锁。', 'zh-hant':'全部5個車位已解鎖。', ja:'全5カースロットを解放しました。', ko:'자동차 슬롯 5개 모두 해제되었습니다.', ar:'تم فتح جميع فتحات السيارات الخمس.', hi:'सभी 5 कार स्लॉट अनलॉक हो गए।', it:'Tutti i 5 slot auto sbloccati.', nl:'Alle 5 autoplaatsen ontgrendeld.', pl:'Wszystkie 5 miejsc na samochody odblokowane.', tr:'5 araba yuvasının tümü açıldı.', id:'Semua 5 slot mobil dibuka.', vi:'Đã mở khóa tất cả 5 ô xe.', th:'ปลดล็อคช่องรถทั้ง 5 ช่องแล้ว', uk:'Усі 5 слотів авто розблоковано.', sv:'Alla 5 bilplatser upplåsta.', da:'Alle 5 bilpladser låst op.', fi:'Kaikki 5 autopaikkaa avattu.', no:'Alle 5 bilplasser låst opp.', cs:'Všechna 5 místa pro auta odemčena.', hu:'Mind az 5 autóhely feloldva.', ro:'Toate cele 5 locuri de mașini deblocate.', el:'Και οι 5 θέσεις αυτοκινήτων ξεκλειδώθηκαν.', ms:'Semua 5 slot kereta dibuka kunci.', fa:'همه ۵ جایگاه ماشین باز شدند.' },
    'toast.money_maxed':      { en:'Money set to maximum.', fr:'Argent fixé au maximum.', es:'Dinero establecido al máximo.', de:'Geld auf Maximum gesetzt.', pt:'Dinheiro definido ao máximo.', ru:'Деньги установлены на максимум.', 'zh-hans':'金钱已设置为最大值。', 'zh-hant':'金錢已設置為最大值。', ja:'お金を最大値に設定しました。', ko:'돈이 최대로 설정되었습니다.', ar:'تم تعيين المال إلى الحد الأقصى.', hi:'पैसे अधिकतम पर सेट किए गए।', it:'Denaro impostato al massimo.', nl:'Geld op maximum ingesteld.', pl:'Pieniądze ustawione na maksimum.', tr:'Para maksimuma ayarlandı.', id:'Uang diatur ke maksimum.', vi:'Tiền đã đặt ở mức tối đa.', th:'เงินถูกตั้งเป็นสูงสุดแล้ว', uk:'Гроші встановлено на максимум.', sv:'Pengar inställda på maximum.', da:'Penge sat til maksimum.', fi:'Rahat asetettu maksimiin.', no:'Penger satt til maksimum.', cs:'Peníze nastaveny na maximum.', hu:'A pénz maximumra van állítva.', ro:'Banii setați la maximum.', el:'Τα χρήματα ορίστηκαν στο μέγιστο.', ms:'Wang ditetapkan ke maksimum.', fa:'پول به حداکثر تنظیم شد.' },
    'toast.no_save':          { en:'No save loaded.', fr:'Aucune sauvegarde chargée.', es:'Ningún guardado cargado.', de:'Kein Spielstand geladen.', pt:'Nenhum save carregado.', ru:'Нет загруженного сохранения.', 'zh-hans':'未加载存档。', 'zh-hant':'未載入存檔。', ja:'セーブが読み込まれていません。', ko:'세이브가 없습니다.', ar:'لم يتم تحميل أي حفظ.', hi:'कोई सेव लोड नहीं।', it:'Nessun salvataggio caricato.', nl:'Geen save geladen.', pl:'Brak wczytanego zapisu.', tr:'Kayıt yüklenmedi.', id:'Tidak ada simpanan yang dimuat.', vi:'Chưa tải bản lưu.', th:'ยังไม่โหลดเซฟ', uk:'Немає завантаженого збереження.', sv:'Ingen sparfil laddad.', da:'Ingen gemfil indlæst.', fi:'Ei tallennusta ladattu.', no:'Ingen lagring lastet inn.', cs:'Žádná uložená hra nenačtena.', hu:'Nincs betöltött mentés.', ro:'Nicio salvare încărcată.', el:'Δεν φορτώθηκε καμία αποθήκευση.', ms:'Tiada simpanan dimuatkan.', fa:'هیچ ذخیره‌ای بارگذاری نشده.' },
    'toast.save_downloaded':  { en:'Modified save downloaded.', fr:'Sauvegarde modifiée téléchargée.', es:'Guardado modificado descargado.', de:'Geänderter Spielstand heruntergeladen.', pt:'Save modificado baixado.', ru:'Изменённое сохранение скачано.', 'zh-hans':'修改后的存档已下载。', 'zh-hant':'修改後的存檔已下載。', ja:'変更したセーブをダウンロードしました。', ko:'수정된 세이브가 다운로드되었습니다.', ar:'تم تنزيل الحفظ المعدّل.', hi:'संशोधित सेव डाउनलोड हुआ।', it:'Salvataggio modificato scaricato.', nl:'Gewijzigde save gedownload.', pl:'Zmodyfikowany zapis pobrany.', tr:'Değiştirilmiş kayıt indirildi.', id:'Simpanan yang dimodifikasi diunduh.', vi:'Bản lưu đã chỉnh sửa được tải xuống.', th:'ดาวน์โหลดเซฟที่แก้ไขแล้ว', uk:'Змінене збереження завантажено.', sv:'Modifierad sparfil nedladdad.', da:'Modificeret gemfil downloadet.', fi:'Muokattu tallennus ladattu.', no:'Endret lagring lastet ned.', cs:'Upravená uložená hra stažena.', hu:'Módosított mentés letöltve.', ro:'Salvarea modificată descărcată.', el:'Η τροποποιημένη αποθήκευση λήφθηκε.', ms:'Simpanan yang diubah suai dimuat turun.', fa:'ذخیره اصلاح شده دانلود شد.' },
    'toast.backup_downloaded':{ en:'Original backup (.bak) downloaded.', fr:'Sauvegarde originale (.bak) téléchargée.', es:'Copia de seguridad original (.bak) descargada.', de:'Originales Backup (.bak) heruntergeladen.', pt:'Backup original (.bak) baixado.', ru:'Оригинальная резервная копия (.bak) скачана.', 'zh-hans':'原始备份（.bak）已下载。', 'zh-hant':'原始備份（.bak）已下載。', ja:'元のバックアップ（.bak）をダウンロードしました。', ko:'원본 백업(.bak)이 다운로드되었습니다.', ar:'تم تنزيل النسخة الاحتياطية الأصلية (.bak).', hi:'मूल बैकअप (.bak) डाउनलोड हुआ।', it:'Backup originale (.bak) scaricato.', nl:'Origineel backup (.bak) gedownload.', pl:'Oryginalna kopia zapasowa (.bak) pobrana.', tr:'Orijinal yedek (.bak) indirildi.', id:'Cadangan asli (.bak) diunduh.', vi:'Bản sao lưu gốc (.bak) đã được tải xuống.', th:'ดาวน์โหลดสำรองต้นฉบับ (.bak) แล้ว', uk:'Оригінальна резервна копія (.bak) завантажена.', sv:'Originalt backup (.bak) nedladdat.', da:'Originalt backup (.bak) downloadet.', fi:'Alkuperäinen varmuuskopio (.bak) ladattu.', no:'Originalt sikkerhetskopi (.bak) lastet ned.', cs:'Originální záloha (.bak) stažena.', hu:'Eredeti biztonsági mentés (.bak) letöltve.', ro:'Backup original (.bak) descărcat.', el:'Το αρχικό αντίγραφο ασφαλείας (.bak) λήφθηκε.', ms:'Sandaran asal (.bak) dimuat turun.', fa:'نسخه پشتیبان اصلی (.bak) دانلود شد.' },
    'toast.load_save_first':  { en:'Load a save file first.', fr:'Chargez d\'abord un fichier de sauvegarde.', es:'Carga primero un archivo de guardado.', de:'Lade zuerst eine Speicherdatei.', pt:'Carregue um arquivo de save primeiro.', ru:'Сначала загрузите файл сохранения.', 'zh-hans':'请先加载存档文件。', 'zh-hant':'請先載入存檔文件。', ja:'まずセーブファイルを読み込んでください。', ko:'먼저 세이브 파일을 불러오세요.', ar:'حمّل ملف الحفظ أولاً.', hi:'पहले सेव फ़ाइल लोड करें।', it:'Carica prima un file di salvataggio.', nl:'Laad eerst een savebestand.', pl:'Najpierw wczytaj plik zapisu.', tr:'Önce bir kayıt dosyası yükle.', id:'Muat file simpanan terlebih dahulu.', vi:'Hãy tải tệp lưu trước.', th:'โหลดไฟล์เซฟก่อน', uk:'Спочатку завантажте файл збереження.', sv:'Ladda in en sparfil först.', da:'Indlæs en gemfil først.', fi:'Lataa ensin tallennustiedosto.', no:'Last inn en lagringsfil først.', cs:'Nejprve načtěte soubor uložené hry.', hu:'Először töltsön be egy mentésfájlt.', ro:'Încărcați mai întâi un fișier de salvare.', el:'Φορτώστε πρώτα ένα αρχείο αποθήκευσης.', ms:'Muatkan fail simpanan dahulu.', fa:'ابتدا یک فایل ذخیره بارگذاری کنید.' }
  };

  /* ─────────────────────────────────────────────────────────
     FALLBACK CHAIN
  ───────────────────────────────────────────────────────── */
  var FALLBACK = 'en';

  /* ─────────────────────────────────────────────────────────
     PUBLIC API
  ───────────────────────────────────────────────────────── */
  var ptI18n = {

    /**
     * Current active language code.
     */
    lang: FALLBACK,

    /**
     * All supported language codes.
     */
    langs: [
      'en','fr','es','de','pt','ru','zh-hans','zh-hant',
      'ja','ko','ar','hi','it','nl','pl','tr','id','vi',
      'th','uk','sv','da','fi','no','cs','hu','ro','el','ms','fa'
    ],

    /**
     * Translate a key, optionally interpolating variables.
     * Variables are written as {varName} in the string.
     * @param {string} key
     * @param {Object} [vars]
     * @returns {string}
     */
    t: function (key, vars) {
      var entry = dict[key];
      if (!entry) return key;
      var str = entry[this.lang] || entry[FALLBACK] || key;
      if (vars) {
        str = str.replace(/\{(\w+)\}/g, function (_, k) {
          return vars[k] !== undefined ? vars[k] : '{' + k + '}';
        });
      }
      return str;
    },

    /**
     * Walk the DOM and apply translations to all elements
     * that carry data-i18n* attributes.
     * @param {string} [langCode]
     */
    apply: function (langCode) {
      if (langCode) this.lang = langCode;

      // Update <html lang> attribute
      document.documentElement.lang = this.lang;

      // data-i18n → textContent
      var els = document.querySelectorAll('[data-i18n]');
      for (var i = 0; i < els.length; i++) {
        var key = els[i].getAttribute('data-i18n');
        els[i].textContent = this.t(key);
      }

      // data-i18n-placeholder → placeholder
      var phEls = document.querySelectorAll('[data-i18n-placeholder]');
      for (var j = 0; j < phEls.length; j++) {
        var phKey = phEls[j].getAttribute('data-i18n-placeholder');
        phEls[j].placeholder = this.t(phKey);
      }

      // data-i18n-title → title attribute
      var titleEls = document.querySelectorAll('[data-i18n-title]');
      for (var k = 0; k < titleEls.length; k++) {
        var tKey = titleEls[k].getAttribute('data-i18n-title');
        titleEls[k].title = this.t(tKey);
      }

      // data-i18n-label → aria-label
      var labelEls = document.querySelectorAll('[data-i18n-label]');
      for (var l = 0; l < labelEls.length; l++) {
        var lKey = labelEls[l].getAttribute('data-i18n-label');
        labelEls[l].setAttribute('aria-label', this.t(lKey));
      }
    },

    /**
     * Initialise: read saved language, sync selectors, apply.
     * Supports both 'pt-lang-select' (portal) and 'sde-lang-select' (editor).
     */
    init: function () {
      var saved = localStorage.getItem('pt-lang') || FALLBACK;
      this.lang = saved;

      // Sync whichever selector exists on this page
      var selIds = ['pt-lang-select', 'sde-lang-select', 'mwe-lang-select'];
      for (var i = 0; i < selIds.length; i++) {
        var sel = document.getElementById(selIds[i]);
        if (sel) {
          sel.value = saved;
          (function (selector, self) {
            selector.addEventListener('change', function () {
              localStorage.setItem('pt-lang', this.value);
              self.apply(this.value);
            });
          })(sel, this);
        }
      }

      this.apply();
    }
  };

  window.ptI18n = ptI18n;

})(window);
